<a href="https://colab.research.google.com/github/MamontLara/Python_for_data_analyst_homeworks/blob/main/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22hw_3_4_apply%2C_groupby%2C_pivot_table_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Домашнє завдання до тем apply(), groupby(), pivot_table()

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

В цьому домашньому завданні продовжуємо працювати з набором даних `supermarket_sales.csv`.

0. Імпортуйте бібліотеку pandas та зчитайте дані у змінну `df` типу `pandas.DataFrame`.

In [2]:
import pandas as pd
df = pd.read_csv('drive/MyDrive/Dataset/supermarket_sales.csv')

1. Дослідимо, який філіал супермаркету ('Branch') є найприбутковішим. Для цього знайдіть сумарний прибуток за кожним філіалом і виявіть, який філіал має найвищий.

In [3]:
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3

In [4]:
df.groupby('Branch')['gross income'].sum()

Branch
A    5057.1605
B    5057.0320
C    5265.1765
Name: gross income, dtype: float64

2. В якому місті знайходиться філіал з найвищим прибутком? Може в тому місці нам розмітисти ще один магазин.  
Знайдіть відповідь за допомогою функціоналу Pandas.

Філіал з найбільшим прибутком знаходиться у місті Naypyitaw.

In [5]:
df.groupby('City')['Quantity'].count()

City
Mandalay     332
Naypyitaw    328
Yangon       340
Name: Quantity, dtype: int64

In [6]:
total_sale = df.groupby('City')['Quantity'].sum()
print(total_sale)

City
Mandalay     1820
Naypyitaw    1831
Yangon       1859
Name: Quantity, dtype: int64

In [9]:
average_profit_per_sale1 = df[df['City'] == 'Naypyitaw']['gross income'].sum() / total_sale.Naypyitaw
print(average_profit_per_sale1)
average_profit_per_sale2= df[df['City'] == 'Naypyitaw']['gross income'].sum() / total_sale.Mandalay
print(average_profit_per_sale2)
average_profit_per_sale3 = df[df['City'] == 'Naypyitaw']['gross income'].sum() / total_sale.Yangon
print(average_profit_per_sale3)

2.87557427635172
2.8929541208791205
2.8322627756858525


Для прийнятт рішення про відкриття нового магазину у місті зпотрібно дослідити економічні та демографічні умови, а також витрати на оренду та логістику, що є основним для такого рішення. З даних видно, що у місті Naypyitaw найбільші прибутки не за кількістю покупок, а отже скоріш за все там проживають/купують багатші верстви населення. Потрібно дослідити конкуренцію у цьому сегменті.

Можливо, також потрібно дослідити альтернативні міста: інші міста з хорошими фінансовими показниками, але меншими витратами.

3.1. Створіть зводну таблицю, яка покаже, скільки покупок (інвойсів) було зроблено в кожній з філій (`Branch`) за різними категоріями товарів. Запишіть таблицю в змінну `invoices_by_category` і виведіть змінну на екран.
Ця таблиця допоможе проаналізувати, в якій філії купують найбільше товарів кожної з категорій.

In [10]:
invoices_by_category = pd.pivot_table(df, values='Invoice ID', index='Branch', columns='Product line', aggfunc='count')
display(invoices_by_category)

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Branch,,,,,,
A,60,51,58,47,65,59
B,55,62,50,53,50,62
C,55,65,66,52,45,45

Очікуваний результат:

![](https://drive.google.com/uc?export=view&id=1rueAdko6S3UxIHGtojetTxlES-EyM6Yb)

3.2. Викристовуючи змінну `invoices_by_category` дайте відповідь програмно (тобто значення треба не просто знайти очима, а вивести за допомогою коду), в якому філіалі магазину (`Branch`) найбільше інвойсів із покупкою товарів категорії "Електронні аксесуари" (`Electronic accessories`)?

In [11]:
max_Electronic_accessories = invoices_by_category['Electronic accessories'].idxmax()
display(max_Electronic_accessories)

'A'

4-6. **Творче завдання на розвиток аналітичного мислення**

Крок 1. Сформулюйте ТРИ питання (гіпотези) до наявних даних, які допомогли б вам зрозуміти, які користувачі що, де та коли найбільше/найменше купують, аби дати на основі цих гіпотез рекомендації бізнесу. Звісно питання мають бути не тими, на які ми вже відповіли в завданнях модулю.

Крок 2. Знайдіть відповіді на свої питання з допомогою функціоналу pandas.

Крок 3. Напишіть, як відповідь на це питання може бути використана для прийняття бізнес рішень.   
   
 Питання можуть бути будь-якої складності, але їх має бути 3. Кожне питання оцінюється як 1 завдання. Без виконання цього завдання ДЗ не приймається. Якщо є питання щодо виконання - пишіть у чат 🙌

***Гіпотеза 1.***

З таблиці invoices_by_category бачимо, що у Branch "A" найменше інфойсів у категоріях Health and beauty та Fashion accessories. Це доволі "жіночі" типи категорій. Тому можемо дослідити відсоток чоловіків та жінок, що здійснюють покупки у Branch "A", тобто у місті Yangon.

In [12]:
#обираємо відповідне місто
filtered_city = df[df['City'] == 'Yangon']
# рахуємо відсоткове значення покупок відповідно до статі
gender_counts = filtered_city['Gender'].value_counts(normalize=True)
display(gender_counts*100)

Gender
Male      52.647059
Female    47.352941
Name: proportion, dtype: float64

Виявилося, що жінки здійснюють менше покупок у місті Yangon. Щоб підвищити продажі серед жінок у цьому місті, слід зосередити увагу на таких аспектах:

*Розташування відділів:*

Потрібно переглянути розташування відділів, орієнтованих на жіночу аудиторію, у магазині міста Yangon; перевірити, щоб вони були в зручних та видимих місцях.

*Оформлення відділів:*

Необхідно подбати про оновлення оформлення відділів, що пропонують жіночий асортимент, врахувати сучасні тренди та уподобання жінок, створити привабливий і комфортний простір.

*Асортимент:*

Переглянути асортимент товарів для жінок у магазинах міста Yangon. Забезпечте різноманіття товарів, яке відповідає смакам та потребам місцевих споживачів.


Завдяки цим крокам можна підвищити привабливість магазину для жінок у місті Yangon та стимулювати їхні покупки.

***Гіпотеза 2.***

Розбивка по місяцях.

Дослідимо кількість покупок по місяцях.

In [13]:
# відберемо лише місяць
def get_month(Date):
    return int(Date.split('/')[0])

In [14]:
# створимо колонку по місяцях
df['month'] = df.Date.apply(get_month)
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating,month
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1,1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6,3
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4,3
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4,1
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3,2

In [15]:
# кількість покупок по місяцях
df['month'].value_counts()

month
1    352
3    345
2    303
Name: count, dtype: int64

In [16]:
# підрахуємо прибуток по місяцях
monthly_profit = df.groupby(df['month'])['gross income'].sum()
display(monthly_profit)

month
1    5537.708
2    4629.494
3    5212.167
Name: gross income, dtype: float64

Аналіз даних показав, що кількість покупок та прибуток значно зменшуються у лютому, відразу після святкового періоду в січні. Це свідчить про сезонний спад активності покупців. Для підвищення продажів у лютому необхідно організувати ефективні акції, розпродажі та нові пропозиції. Оптимальним буде розпочати рекламну кампанію вже в січні, щоб забезпечити успішний результат у лютому.

***Гіпотеза 3.***

Ефективність статуту учасника клубу.

Дослідимо, як відрізняються покупки учасників клубу магазину та просто покупців.

In [17]:
# кількість покупок згідно з типом покупця
df['Customer type'].value_counts()

Customer type
Member    501
Normal    499
Name: count, dtype: int64

In [18]:
# прибуток по категоріях за типами покупців
invoices_by_member = pd.pivot_table(df, values='gross income', index='Customer type', columns='Product line', aggfunc='sum')
display(invoices_by_member)

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Customer type,,,,,,
Member,1166.5950,1253.522,1493.220,1230.0495,1332.287,1344.4905
Normal,1420.9065,1332.473,1180.344,1112.5095,1232.566,1280.4060

In [19]:
# середня вартість чеку
invoices_by_member_price = pd.pivot_table(df, values='Unit price', index='Customer type', columns='Product line', aggfunc='mean')
display(invoices_by_member_price)

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Customer type,,,,,,
Member,55.278205,56.776395,58.080638,56.069041,55.120241,55.604943
Normal,52.087717,57.506304,53.574500,53.732152,55.528961,58.522152

Згідно з даними, різниця в кількості покупок, середньому чеку та прибутку між членами клубу магазину і простими покупцями є незначною, часто не перевищує 10%, іноді прибуток від простих покупців навіть вищий. Це свідчить про те, що поточна політика клубної програми є неефективною.

Можливі причини:

*1. Недостатня привабливість клубної програми*

Члени клубу не отримують значних переваг, які б спонукали їх робити більше покупок. Це може означати, що програма лояльності або клубна програма не є достатньо привабливою або вигідною, щоб мотивувати членів купувати частіше.

*2. Схожі рівні покупок*

Можливо, що загальна привабливість магазину або продуктів є основним фактором, і рівень покупок не залежить від статусу члена клубу. Це може свідчити про те, що всі покупці, незалежно від їх статусу, мають подібні вподобання і купують у магазині з однаковою частотою.

*3. Ефективність маркетингових акцій*

Можливо, маркетингові акції і пропозиції однаково впливають на обидві групи покупців. Це може вказувати на те, що акції ефективні як для членів клубу, так і для простих покупців, і не створюють додаткової мотивації для більш частих покупок членів клубу.